name: MutalkCI


on:
  push:
    branches: [ master ]
    paths:
      - '**.st'
  pull_request:
    branches: [ master ]
    paths:
      - '**.st'

  workflow_dispatch:
    inputs:
        mode:
          description: 'modes: full (run on all project), diff (run on the last commit diff), commit (especify a commit to calculate diff)'
          required: true
          default: 'diff'
        commit:
          description: 'If mode == commit, here you enter the Commid id/name/shortId to evaluate the diff'
          required: false
          default: ''

jobs:
  eventBased:
    runs-on: ubuntu-latest
    if: github.event_name != 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v2

      - uses: hpi-swa/setup-smalltalkCI@v1
        id: smalltalkci
        with:
          smalltalk-version: Pharo64-stable

      - run: smalltalkci -s ${{ steps.smalltalkci.outputs.smalltalk-version }}
        shell: bash
        timeout-minutes: 15

      - run: ${{env.SMALLTALK_CI_VM}} ${{env.SMALLTALK_CI_IMAGE}} metacello install "github://mabdi/mutalk/src" BaselineOfMuTalk
        shell: bash
      
      - run: ${{env.SMALLTALK_CI_VM}} ${{env.SMALLTALK_CI_IMAGE}} mutalk --project=${{github.event.repository.name}} --diff
        shell: bash

      - uses: actions/upload-artifact@v2
        with:
          name: mutation-testing-output
          path: ${{env.SMALLTALK_CI_BUILD_BASE}}/__mutalk_export.json

      - id: pushjson
        uses: actions/github-script@v4
        with:
          script: |
            const fs = require('fs')
            const data = fs.readFileSync(process.env.SMALLTALK_CI_BUILD_BASE + '/__mutalk_export.json', 'utf8')
            const url = 'https://mutation-testing-coverage.herokuapp.com/api/v1/jobs/'
            fetch(url, {
                method: 'POST', 
                headers: {
                  'Content-Type': 'application/json'
                },
                body: JSON.stringify(data)
              });
         
  manual:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v2

      - uses: hpi-swa/setup-smalltalkCI@v1
        id: smalltalkci
        with:
          smalltalk-version: Pharo64-stable

      - id: parseston
        uses: actions/github-script@v4
        with:
          script: |
            const fs = require('fs')
            //const core = require('@actions/core');

            const linesstonfile = fs.readFileSync(process.env.GITHUB_WORKSPACE + '/.smalltalk.ston', 'utf8').split("\n")
            for(var s of linesstonfile) {
                //console.log(s)
                if(s.trim().startsWith('#baseline')){
                    const baseline = s.trim().substring('#baseline : \''.length, s.trim().length -2)
                    console.log(baseline)
                    core.exportVariable('CI_baseline', baseline);
                }
                if(s.trim().startsWith('#directory')){
                    directory = s.trim().substring('#directory : \''.length, s.trim().length -2)
                    console.log(directory)
                    core.exportVariable('CI_directory', directory);
                }
            }
            
      - run: smalltalkci -s ${{ steps.smalltalkci.outputs.smalltalk-version }}
        shell: bash
        timeout-minutes: 15

      - run: ${{env.SMALLTALK_CI_VM}} ${{env.SMALLTALK_CI_IMAGE}} metacello install "github://$GITHUB_REPOSITORY/$CI_directory" BaselineOf${{env.CI_baseline}}
        shell: bash
        
      - run: ${{env.SMALLTALK_CI_VM}} ${{env.SMALLTALK_CI_IMAGE}} metacello install "github://mabdi/mutalk/src" BaselineOfMuTalk
        shell: bash

      - name: full mutation testing
        if: github.event.inputs.mode == 'full'
        run: ${{env.SMALLTALK_CI_VM}} ${{env.SMALLTALK_CI_IMAGE}} mutalk --project=${{github.event.repository.name}} 

      - name: diff mutation testing
        if: github.event.inputs.mode == 'diff'
        run: ${{env.SMALLTALK_CI_VM}} ${{env.SMALLTALK_CI_IMAGE}} mutalk --project=${{github.event.repository.name}}  --diff

      - name: commit mutation testing
        if: github.event.inputs.mode == 'commit'
        run: ${{env.SMALLTALK_CI_VM}} ${{env.SMALLTALK_CI_IMAGE}} mutalk --project=${{github.event.repository.name}} --commit=${{github.event.inputs.commit}}

      - uses: actions/upload-artifact@v2
        with:
          name: mutation-testing-output
          path: ${{env.SMALLTALK_CI_BUILD_BASE}}/__mutalk_export.json
