name: SmallAmpCI
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  reponame: ${{github.event.repository.name}}

on:
  workflow_dispatch:

jobs:
  TestAmplification:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        portion: [1,2] # the content of array is not important, just the length
    name: Job number ${{ strategy.job-index }}
    steps:
      - uses: actions/checkout@v2
      - uses: hpi-swa/setup-smalltalkCI@v1
        id: smalltalkci
        with:
          smalltalk-version: Pharo64-8.0
      - run: smalltalkci -s ${{ steps.smalltalkci.outputs.smalltalk-version }}
        shell: bash
        timeout-minutes: 15
      - uses: mabdi/smallamp-action@main
      - run: smallAmpCI 
        shell: bash
        env:
          # you can also use: ${{ matrix.portion }}
          SMALLAMP_PORTION: ${{ strategy.job-index }} 
          SMALLAMP_ALLJOBS: ${{ strategy.job-total }}
