name: SmallAmp
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  reponame: ${{github.event.repository.name}}
  project_baseline: SmallBank
  project_directory: src
  iteration: 3
  maxInputs: 10
  mode: dspotFast

on:
  workflow_dispatch:
        
jobs:
  TestAmplification:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        portion: [1 , 2] # Change me if you like. The content of array is not important, just the length
    name: Job number ${{ strategy.job-index }}
    steps:
      - uses: actions/checkout@v2
        with:
           fetch-depth: 0
      - uses: mabdi/smallamp-action@main
        with:
          action: setup
      - uses: mabdi/smallamp-action@main
        with:
          action: amplify
        env:
          SMALLAMP_PORTION: ${{ strategy.job-index }} 
          SMALLAMP_ALLJOBS: ${{ strategy.job-total }}
          SMALLAMP_iteration: ${{ env.iteration }}
          SMALLAMP_maxInputs: ${{ env.maxInputs }}
          SMALLAMP_mode: ${{ env.mode }}  
  TestAmplificationPush:
    runs-on: ubuntu-latest
    needs: TestAmplification
    steps:
      - uses: actions/checkout@v2
        with:
           fetch-depth: 0
      - uses: mabdi/smallamp-action@main
        with:
          action: setup
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          path: ${{ env.PHARO_HOME }}
      - uses: mabdi/smallamp-action@main
        with:
          action: push
          github-token: ${{secrets.GITHUB_TOKEN}}
          
