name: SmallAmpCIDbg
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  reponame: ${{github.event.repository.name}}
  project_baseline: SmallBank
  project_directory: src
  

on:
  workflow_dispatch:
        
jobs:
  TestAmplificationSetup:
    runs-on: ubuntu-latest
    steps:
      - uses: mabdi/smallamp-action@reimp
        with:
          action: setup
      
